---
- name: Run Nomad job from template
  hosts: nmaster  # Change to your Nomad client hostname
  become: true  # Required for interacting with Nomad
  vars:
    jenkins_master_exists: false
    template_path: '../templates/jenkins-master.hcl.j2'

  tasks:
    - include_vars: ../vars/main.yml
    - include_vars: ../../../host_vars/main.yml

    - name: Install Prerequisites
      apt:
        name: python3-pip  # Install python2 pip
        state: present

    - name: install pre-requisites
      pip:
        state: present
        executable: pip3
        name:
          - python-nomad

    - name: Get all Jobs in Nomad 1 - Get response
      community.general.nomad_job_info: 
        host: "{{ nmaster_ip_address }}"
        use_ssl: false
      register: response
    
    - name: Get all Jobs in Nomad 2 - get .result key from response
      set_fact:
        job_list: "{{ response.result }}"

    - name: Show Nomad Jobs
      ansible.builtin.debug:
        msg: "{{ job_list }}"
      
    - name: Establish if jenkins-master exists
      ansible.builtin.set_fact:
        jenkins_master_exists: true
      loop: "{{ job_list }}"
      when: '"{{ nomad_job_name }}" in item.Name'

    - name: Delete Nomad job if exists
      community.general.nomad_job:
        host:  localhost
        state: absent
        content: "{{ lookup('ansible.builtin.file', '{{ template_path }}') }}"
        timeout: 5
        use_ssl: false
      when: jenkins_master_exists


    - name: Run Nomad job
      community.general.nomad_job:
        host:  localhost
        state: present
        content: "{{ lookup('ansible.builtin.file', '{{ template_path }}') }}"
        timeout: 5
        use_ssl: false
      vars: 
        - job_name: "{{ nomad_job_name }}"

  # Choose one of the "Run Nomad job" tasks based on your group usage