---
- name: Run Nomad job from template
  hosts: nclient1  # Change to your Nomad client hostname
  become: true  # Required for interacting with Nomad
  vars:
    gitea_exists: false

  tasks:
    - include_vars: ../vars/main.yml
    - include_vars: ../../../host_vars/main.yml

    - name: Pull Gitea Docker image
      docker_image:
        name: "{{ docker_image_gitea }}"
        state: present
        source: pull  # Explicitly specify pulling the image

    - name: Pull Mysql Docker image
      docker_image:
        name: "{{ docker_image_mysql }}"
        state: present
        source: pull  # Explicitly specify pulling the image
    
    - name: Create a Docker Volume for Gitea
      docker_volume:
        name: "{{ docker_volume_gitea }}"
        state: present
      become: false

    - name: Create a Docker Volume for Mysql
      docker_volume:
        name: "{{ docker_volume_mysql }}"
        state: present
      become: false

    - name: Install Prerequisites
      apt:
        name: python3-pip  # Install python2 pip
        state: present

    - name: install pre-requisites
      pip:
        state: present
        executable: pip3
        name:
          - python-nomad

    - name: Get all Jobs in Nomad 1 - Get response
      community.general.nomad_job_info: 
        host: "{{ nmaster_ip_address }}"
        use_ssl: false
      register: response
    
    - name: Get all Jobs in Nomad 2 - get .result key from response
      set_fact:
        job_list: "{{ response.result }}"

    - name: Show Nomad Jobs
      ansible.builtin.debug:
        msg: "{{ job_list }}"
      
    - name: Establish if gitea exists
      ansible.builtin.set_fact:
        gitea_exists: true
      loop: "{{ job_list }}"
      when: '"{{ nomad_job_name }}" in item.Name'

    - name: Delete gitea itlab job if exists
      community.general.nomad_job:
        host:  localhost
        state: absent
        content: "{{ lookup('ansible.builtin.file', '{{ ansible_dir }}/gitea/templates/gitea.hcl') }}"
        timeout: 5
        use_ssl: false
      when: gitea_exists

    - name: create Gitea Template
      template: 
        src: "{{ ansible_dir }}/gitea/templates/gitea.hcl.j2"
        dest: "{{ ansible_dir }}/gitea/templates/gitea.hcl"
      become: false
      delegate_to: localhost
      vars:
        - job_name: "{{ nomad_job_name }}"
        - docker_image_gitea: "{{ docker_image_gitea }}"
        - docker_image_mysql: "{{ docker_image_mysql }}"
        - docker_volume_gitea: "{{ docker_volume_gitea }}"
        - docker_volume_mysql: "{{ docker_volume_mysql }}"


    - name: Run gitlab Nomad job
      community.general.nomad_job:
        host:  localhost
        state: present
        content: "{{ lookup('ansible.builtin.file', '{{ ansible_dir }}/gitea/templates/gitea.hcl') }}"
        timeout: 5
        use_ssl: false
      vars: 
        - job_name: "{{ nomad_job_name }}"
        - docker_image_gitea: "{{ docker_image_gitea }}"
        - docker_image_mysql: "{{ docker_image_mysql }}"
        - docker_volume_gitea: "{{ docker_volume_gitea }}"
        - docker_volume_mysql: "{{ docker_volume_mysql }}"

  # Choose one of the "Run Nomad job" tasks based on your group usage