- name: Run HAProxy container
  hosts: consul
  become: yes
  vars:
    template_folder: ../templates
  tasks:
    - name: Create HAProxy configuration directory
      file:
        path: /etc/haproxy
        state: directory
    - name: Create HAProxy configuration file
      template:
        src: "{{ template_folder }}/haproxy.cfg"  # Replace with your HAProxy configuration template
        dest: /etc/haproxy/haproxy.cfg
      notify:
        - Restart HAProxy container
    - name: Ensure HAProxy container is running
      community.docker.docker_container:
        name: haproxy
        image: haproxy:latest
        state: started
        user: root
        detach: true
        network_mode: host
        volumes:
          - "/etc/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
          
  handlers:
    - name: Restart HAProxy container
      docker_container:
        name: haproxy
        state: started
        recreate: yes