---
- name: Run Consul container
  hosts: consul_client
  become: yes
  vars:
    - consul_bind_address: "{{ bind_address | default('192.168.217.103') }}"
    - consul_bind_last_octet: "{{ ansible_default_ipv4.address.split('.')[-1] }}"
  tasks:
    - name: Ensure Consul container is running
      community.docker.docker_container:
        name: consul
        image: consul:latest
        state: started
        detach: true
        tty: true
        network_mode: host
        command: >
          agent -node=client-{{ consul_bind_last_octet }} -retry-join={{ consul_bind_address }} -bind={{ ansible_default_ipv4.address }}