---
- name: Run Consul container
  hosts: consul
  become: yes
  vars:
    - consul_bind_address: "{{ bind_address | default('192.168.217.103') }}"
  tasks:
    - name: Ensure Consul container is running
      community.docker.docker_container:
        name: consul
        image: consul:latest
        state: started
        detach: true
        tty: true
        network_mode: host
        command: >
          agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0 -bind={{ consul_bind_address }}