---
- name: Provision Nomad Client
  hosts: nomad_client
  vars:
    consul_endpoint: "http://consul.example.com"
    nomad_service: "nomad"
  tasks:
    - name: Query Consul for Nomad master IP
      uri:
        url: "{{ consul_endpoint }}/v1/catalog/service/{{ nomad_service }}"
        return_content: yes
      register: consul_response
      delegate_to: localhost
      become: false
    
    - name: Parse Nomad master IP
      set_fact:
        nomad_master_ip: "{{ consul_response.json[0].ServiceAddress }}"

    - name: Configure Nomad client
      become: true
      template:
        src: ../../template/nomad_client.hcl.j2
        dest: /etc/nomad.d/nomad.hcl
      vars:
        nomad_master_ip: "{{ nomad_master_ip }}"
      notify: restart nomad client

  handlers:
    - name: restart nomad client
      become: true
      service:
        name: nomad
        state: restarted